### ISSUE TITLE
Feature Request : Authentication

### ISSUE THREAD

**Issue by Gibby** [nicksherron/bashhub-server#1]
Support authentication.

Token base would be fine.

I use jwilder/nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion for SSL offloading so that could handle the encryption via https

**Comment by Gibby** [comment]
P.S. Awesome work, been waiting for something like this to switch over to bashhub-client

**Comment by nicksherron** [comment]
Thanks for the feedback!
Currently, authentication is handled with jwt tokens, which I  hadn't had any experience with until recently so the implementation might need some work and better documentation but basically, the workflow is 
 - POST request to /api/v1/user creates a user, salts the password and stores the username and password hash in the db
```
curl  http://localhost:8080/api/v1/user -d '{"registrationCode": "", "username": "user", "password": "pass", "email": "user@example.com"}'
```
- /api/v1/login authenticates user by checking the user and salt hash and returns a access token upon sucessfull lookup.
```
 curl "http://localhost:8080/api/v1/login" -H "Content-Type:application/json" -d '{"username": "user", "password": "pass"}'
{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTczNDYwOTQsIm9yaWdfaWF0IjoxNTgxMzQ2MDk0LCJzeXN0ZW1OYW1lIjoiIiwidXNlcm5hbWUiOiJ1c2VyIn0.IpzpfMuk5wLaie62ShJu0AZL0RmjLjGHEjzfehAd-kQ"}
```
which the bashhub client store in the config file at ``` $BH_HOME_DIRECTORY/config``` and any other endpoints require for access. 

Is that kind of what you're talking about? Or do you think adding something like basic auth as an option
like 
```
curl http://user:password@localhost:8080/any/path
```
would be good to add as well? I'm open to suggestion but I'd like to stay away from anything too complicated like the jwilder/nginx-proxy .  If people want to put something like nginx or apache in front of the bashhub-server (which is probably a good idea) and add their own ssl stuff that's probably best done separately.

**Comment by Gibby** [comment]
I'm setting up the tests right now, I didn't realize that JWT was already setup for the server and client so that should be good. 

Also for nginx/ssl, I was just making the comment that, that is how I offload ssl. Nothing needed on this project since you already built the docker image for bashhub-server.

**Comment by nicksherron** [comment]
> I'm setting up the tests right now, I didn't realize that JWT was already setup for the server and client so that should be good.
> 
Ok good. I'm going to close this then. Thanks for the input, I added the JWT authentication to the readme since it wasn't clear.
