### ISSUE TITLE
Bad practice to write passwords in commands

### ISSUE THREAD

**Issue by andrew-morris** [nicksherron/bashhub-server#12]
https://github.com/nicksherron/bashhub-server#transferring-history-from-bashhubcom

...as they get left in your... uh.... Bash history. Which might.... go to someone else's computer. 

Since this is less likely to be scripted, it is probably okay to either authenticate with a separate command or simply force the user to interactively type their credentials in on the transfer command.

**Comment by nicksherron** [comment]
Yeah, good point. bc7aebe6a66eeddf8476c179e26fe6d22a368dd0 fixes this by adding a default password prompt if the password flags are omitted.
