### ISSUE TITLE
Bug: bashhub status  results in 404 error

### ISSUE THREAD

**Issue by Gibby** [nicksherron/bashhub-server#2]
Everything is working great so far. Found that running `bashhub status` returns the following on the client:
> Sorry, an error occurred communicating with Bashhub. Response Code: 404

On the server I see the following in the logs:
> /api/v1/client-view/status?processId=21596&startTime=1581357553000

**Comment by nicksherron** [comment]
The dev branch has a fix for this along with several other bug fixes/feature additions. Going to do some more testing before merging and will probably push out a release soon thereafter.

**Comment by Gibby** [comment]
Just tested dev branch via docker and it is working for me.

**Comment by nicksherron** [comment]
Great! Thanks for bringing this up. It's been added to master and the newest release v0.2.0
