### ISSUE TITLE
Request build/docker image for arm32v7

### ISSUE THREAD

**Issue by brokencode64** [nicksherron/bashhub-server#6]
Request build/docker image for arm32v7 - qnap/linux

**Comment by nicksherron** [comment]
I added arm-7 to release builds.  The latest one is [bashhub-server_v0.2.3_linux_arm-7.tar.gz](https://github.com/nicksherron/bashhub-server/releases/download/v0.2.3/bashhub-server_v0.2.3_linux_arm-7.tar.gz).  If you want to run it in docker it should be pretty easy to run the binary in something like [arm32v7/alpine](https://hub.docker.com/r/arm32v7/alpine/). Does that help?

**Comment by brokencode64** [comment]
Absolutely!
